name = "example-cf-chat-solid"
main = "./src/cf-worker/index.ts"
compatibility_date = "2025-08-24"
compatibility_flags = ["enable_request_signal", "nodejs_compat"]

[[durable_objects.bindings]]
name = "SYNC_BACKEND_DO"
class_name = "SyncBackendDO"

[[durable_objects.bindings]]
name = "CLIENT_DO"
class_name = "LiveStoreClientDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SyncBackendDO", "LiveStoreClientDO"]

[env.prod]
name = "example-cf-chat-solid"

[[env.prod.durable_objects.bindings]]
name = "SYNC_BACKEND_DO"
class_name = "SyncBackendDO"

[[env.prod.durable_objects.bindings]]
name = "CLIENT_DO"
class_name = "LiveStoreClientDO"

[[env.prod.migrations]]
tag = "v1"
new_sqlite_classes = ["SyncBackendDO", "LiveStoreClientDO"]

[env.preview]
name = "example-cf-chat-solid-preview"

[[env.preview.durable_objects.bindings]]
name = "SYNC_BACKEND_DO"
class_name = "SyncBackendDO"

[[env.preview.durable_objects.bindings]]
name = "CLIENT_DO"
class_name = "LiveStoreClientDO"

[[env.preview.migrations]]
tag = "v1"
new_sqlite_classes = ["SyncBackendDO", "LiveStoreClientDO"]

[env.dev]
name = "example-cf-chat-solid-dev"

[[env.dev.durable_objects.bindings]]
name = "SYNC_BACKEND_DO"
class_name = "SyncBackendDO"

[[env.dev.durable_objects.bindings]]
name = "CLIENT_DO"
class_name = "LiveStoreClientDO"

[[env.dev.migrations]]
tag = "v1"
new_sqlite_classes = ["SyncBackendDO", "LiveStoreClientDO"]

[observability]
enabled = true
