name = "example-web-todomvc-solid"
main = "./src/cf-worker/index.ts"
compatibility_date = "2025-05-08"
compatibility_flags = ["enable_request_signal", "nodejs_compat"]

[env.prod]
name = "example-web-todomvc-solid"

[env.preview]
name = "example-web-todomvc-solid-preview"

[env.dev]
name = "example-web-todomvc-solid-dev"
