/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ModeRouteImport } from './routes/$mode'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModeIndexRouteImport } from './routes/$mode.index'
import { Route as ModeStoreIdClientIdSessionIdSchemaAliasRouteImport } from './routes/$mode.$storeId.$clientId.$sessionId.$schemaAlias'

const ModeRoute = ModeRouteImport.update({
  id: '/$mode',
  path: '/$mode',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModeIndexRoute = ModeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ModeRoute,
} as any)
const ModeStoreIdClientIdSessionIdSchemaAliasRoute =
  ModeStoreIdClientIdSessionIdSchemaAliasRouteImport.update({
    id: '/$storeId/$clientId/$sessionId/$schemaAlias',
    path: '/$storeId/$clientId/$sessionId/$schemaAlias',
    getParentRoute: () => ModeRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$mode': typeof ModeRouteWithChildren
  '/$mode/': typeof ModeIndexRoute
  '/$mode/$storeId/$clientId/$sessionId/$schemaAlias': typeof ModeStoreIdClientIdSessionIdSchemaAliasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$mode': typeof ModeIndexRoute
  '/$mode/$storeId/$clientId/$sessionId/$schemaAlias': typeof ModeStoreIdClientIdSessionIdSchemaAliasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$mode': typeof ModeRouteWithChildren
  '/$mode/': typeof ModeIndexRoute
  '/$mode/$storeId/$clientId/$sessionId/$schemaAlias': typeof ModeStoreIdClientIdSessionIdSchemaAliasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$mode'
    | '/$mode/'
    | '/$mode/$storeId/$clientId/$sessionId/$schemaAlias'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$mode' | '/$mode/$storeId/$clientId/$sessionId/$schemaAlias'
  id:
    | '__root__'
    | '/'
    | '/$mode'
    | '/$mode/'
    | '/$mode/$storeId/$clientId/$sessionId/$schemaAlias'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ModeRoute: typeof ModeRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$mode': {
      id: '/$mode'
      path: '/$mode'
      fullPath: '/$mode'
      preLoaderRoute: typeof ModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$mode/': {
      id: '/$mode/'
      path: '/'
      fullPath: '/$mode/'
      preLoaderRoute: typeof ModeIndexRouteImport
      parentRoute: typeof ModeRoute
    }
    '/$mode/$storeId/$clientId/$sessionId/$schemaAlias': {
      id: '/$mode/$storeId/$clientId/$sessionId/$schemaAlias'
      path: '/$storeId/$clientId/$sessionId/$schemaAlias'
      fullPath: '/$mode/$storeId/$clientId/$sessionId/$schemaAlias'
      preLoaderRoute: typeof ModeStoreIdClientIdSessionIdSchemaAliasRouteImport
      parentRoute: typeof ModeRoute
    }
  }
}

interface ModeRouteChildren {
  ModeIndexRoute: typeof ModeIndexRoute
  ModeStoreIdClientIdSessionIdSchemaAliasRoute: typeof ModeStoreIdClientIdSessionIdSchemaAliasRoute
}

const ModeRouteChildren: ModeRouteChildren = {
  ModeIndexRoute: ModeIndexRoute,
  ModeStoreIdClientIdSessionIdSchemaAliasRoute:
    ModeStoreIdClientIdSessionIdSchemaAliasRoute,
}

const ModeRouteWithChildren = ModeRoute._addFileChildren(ModeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ModeRoute: ModeRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
